"""Initial migration1

Revision ID: 7c9836dd2c16
Revises: 71dd46d1b85a
Create Date: 2022-12-12 12:23:36.348846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7c9836dd2c16"
down_revision = "71dd46d1b85a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("persons")
    op.drop_table("phones")
    op.drop_table("emails")
    op.drop_table("owners")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "owners",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("login", sa.VARCHAR(length=120), nullable=False),
        sa.Column("hash", sa.VARCHAR(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "emails",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("phone_number", sa.VARCHAR(length=120), nullable=False),
        sa.Column("description", sa.VARCHAR(length=120), nullable=True),
        sa.Column("person_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(["person_id"], ["persons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "phones",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("phone_number", sa.VARCHAR(length=120), nullable=False),
        sa.Column("description", sa.VARCHAR(length=120), nullable=True),
        sa.Column("person_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(["person_id"], ["persons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "persons",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("first_name", sa.VARCHAR(length=120), nullable=False),
        sa.Column("last_name", sa.VARCHAR(length=120), nullable=False),
        sa.Column("birth_date", sa.DATE(), nullable=True),
        sa.Column("work_place", sa.VARCHAR(length=120), nullable=True),
        sa.Column("post_name", sa.VARCHAR(length=120), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
