"""Add token_cookie

Revision ID: 87434c971c5a
Revises: f46c964087f6
Create Date: 2022-12-12 15:56:08.153407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "87434c971c5a"
down_revision = "f46c964087f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("owners", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("token_cookie", sa.String(length=255), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("owners", schema=None) as batch_op:
        batch_op.drop_column("token_cookie")

    # ### end Alembic commands ###
